### ISSUE TITLE
Interscript web API

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-api#1]
For API we also need:
- list out all supported systems (key by language code)
- list out system limits (timeout, size limits)

_Originally posted by @ronaldtse in https://github.com/interscript/infrastructure/issues/1#issuecomment-657009964_

**Comment by phuonghuynh** [comment]
@ronaldtse Do you know how could we implement this API? Look like there is no AWS API providing this information. AWS Lambda limits can be found in this link, https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html.

> list out system limits (timeout, size limits)

**Comment by ronaldtse** [comment]
I suggest we use GraphQL for both APIs? Can you design it?

**Comment by phuonghuynh** [comment]
@ronaldtse yes, we can use GraphQL , but I think the data for 2nd API is static?

>list out system limits (timeout, size limits)

**Comment by ronaldtse** [comment]
@phuonghuynh yes, how about just:

GET /limits
```json
{ "message_size_max": "100000", "processing_time_max": "15000" }
```

message_size_max: in bytes
processing_time_max: in ms

?

**Comment by phuonghuynh** [comment]
@ronaldtse just for preview `system_codes` function
```
curl -XPOST 'https://pupd7fpbsa.execute-api.us-east-1.amazonaws.com/prod/interscript' \
  --header 'Content-Type: application/json' \
  --data-raw '{systemCodes}'
```

**Comment by ronaldtse** [comment]
Closing now since it's mostly working.
