### ISSUE TITLE
Not working with GraphiQL

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-api#8]
Download GraphiQL app. e.g. `brew cask install graphiql`

Open GraphiQL, enter API URL and data:

<img width="1212" alt="Screen Shot 2020-07-30 at 12 03 21 AM" src="https://user-images.githubusercontent.com/11865/88823902-35078000-d1f8-11ea-91cc-b618185ebe70.png">

And it doesn't work...

I also tried adding the header, but it still doesn't work.

<img width="1212" alt="Screen Shot 2020-07-30 at 12 04 44 AM" src="https://user-images.githubusercontent.com/11865/88823986-510b2180-d1f8-11ea-94b6-2da84d04bbe3.png">
<img width="1212" alt="Screen Shot 2020-07-30 at 12 05 05 AM" src="https://user-images.githubusercontent.com/11865/88823992-536d7b80-d1f8-11ea-8809-230f7bdbf555.png">

**Comment by ronaldtse** [comment]
@phuonghuynh says:

> just fixed GraphiQL support


<img width="1136" alt="Screen Shot 2020-07-31 at 11 32 12 AM" src="https://user-images.githubusercontent.com/11865/88997120-852e3180-d321-11ea-89e9-8918d12ff004.png">

Seems that it's still broken in another way.

**Comment by phuonghuynh** [comment]
@ronaldtse the error is in gem interscript v0.1.4, 

Rspec report 
[Uploading rspec_results.zip…]()

**Comment by ronaldtse** [comment]
The particular tests for this system are passing:

<img width="872" alt="Screen Shot 2020-08-01 at 1 10 50 AM" src="https://user-images.githubusercontent.com/11865/89059486-d7a83600-d393-11ea-9872-54e88bf0f4d6.png">

The failures are due to the lambda not properly setup with the necessary python installation:

<img width="868" alt="Screen Shot 2020-08-01 at 1 11 42 AM" src="https://user-images.githubusercontent.com/11865/89059541-f6a6c800-d393-11ea-9e82-9f32689d6ecc.png">

**Comment by ronaldtse** [comment]
Fixed. The error with python is another issue.
